server:
  port: 9030

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
     console:
       enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# datasource:
#   driver-class-name: com.mysql.jdbc.Driver
#   url: jdbc:mysql://localhost:3306/negocio
#   username: desarrollo
#   password: desarrollo1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  application:
    name: Persona

management:
  endpoints:
    web:
      exposure:
        include: "*"